### ISSUE TITLE
Error when stopping server

### ISSUE THREAD

**Issue by Kaleran** [BiggerSeries/Phosphophyllite#22]
Forge 40.1.19
Mod latest version

`[11May2022 08:16:38.798] [Server thread/ERROR] [net.minecraft.server.level.ChunkMap/]: Failed to save chunk [59, -40]
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:455) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:426) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:313) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:603) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:543) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:717) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:411) ~[fastutil-8.5.6.jar%2329!/:?]
	at net.roguelogix.phosphophyllite.modular.tile.PhosphophylliteTile.remove(PhosphophylliteTile.java:133) ~[phosphophyllite-1.18.2-0.6.0-beta.1.1.jar%23190!/:0.6.0-beta.1.1]
	at net.roguelogix.phosphophyllite.modular.tile.PhosphophylliteTile.onChunkUnloaded(PhosphophylliteTile.java:117) ~[phosphophyllite-1.18.2-0.6.0-beta.1.1.jar%23190!/:0.6.0-beta.1.1]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_187957_(LevelChunk.java:552) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.level.ServerLevel.m_8712_(ServerLevel.java:865) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at net.minecraft.server.level.ChunkMap.m_202998_(ChunkMap.java:485) ~[server-1.18.2-20220404.173914-srg.jar%23245!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 9 more
`

**Comment by RogueLogix** [comment]
no additional safeties have been put in place, however i haven't seen this repeated, so, im going to close it as a one off
